# Generated by Django 3.0.2 on 2020-01-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('Temp', models.CharField(max_length=1000)),
                ('voltage', models.CharField(max_length=1000)),
                ('current', models.CharField(max_length=1000)),
                ('speed', models.CharField(max_length=1000)),
                ('vibrations', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
